name: Secrets
on: push
jobs:
    prints:
        runs-on: ubuntu-latest
        env:
            SECRET: ${{ secrets.PASSWORD }}
        steps:
            - run: echo "${PASSWORD}"
            - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"